#!/bin/sh

# load GCCVER and BINVER
. ./toolvers

rm -f build.log
rm -rf build-*
rm -rf gcc-$GCCVER
rm -rf binutils-$BINVER
rm -rf gdb-$GDBVER
rm -rf gmp-$GMPVER
rm -rf mpc-$MPCVER
rm -rf mpfr-$MPFRVER
rm -f .extracted-stamp
