#!/usr/bin/env bash

# Build a list of a list of targets I generally keep around.
# Comment out any that are unneeded/unwanted
ARCHES+="aarch64 "
ARCHES+="arm "
ARCHES+="i386 "
ARCHES+="m68k "
ARCHES+="microblaze "
ARCHES+="mips "
ARCHES+="nios2 "
ARCHES+="or1k "
ARCHES+="powerpc "
ARCHES+="riscv32 "
ARCHES+="riscv64 "
ARCHES+="sh "
ARCHES+="sparc "
ARCHES+="x86_64 "

exec ./doit -f -c -s -q -o build -a "$ARCHES"

# vim: ts=4 sw=4 expandtab
